//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombosDetalle
    {
        public string IdCombo { get; set; }
        public int Correlativo { get; set; }
        public string IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Combos Combos { get; set; }
        public virtual ProductosRestaurante ProductosRestaurante { get; set; }
    }
}
