//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosClientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidosClientes()
        {
            this.HistorialPedidos = new HashSet<HistorialPedidos>();
            this.PedidosClientesDetalles = new HashSet<PedidosClientesDetalles>();
            this.TrackeoPedidosClientes = new HashSet<TrackeoPedidosClientes>();
        }
    
        public string IdPedido { get; set; }
        public string IdCliente { get; set; }
        public string TelefonoContacto { get; set; }
        public string DireccionEntrega { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Cancelado { get; set; }
    
        public virtual CuentasClientes CuentasClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialPedidos> HistorialPedidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosClientesDetalles> PedidosClientesDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackeoPedidosClientes> TrackeoPedidosClientes { get; set; }
    }
}
