//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosClientesDetalles
    {
        public int Correlativo { get; set; }
        public string IdPedido { get; set; }
        public string IdObjeto { get; set; }
    
        public virtual PedidosClientes PedidosClientes { get; set; }
    }
}
